Update mod.py
from mod import Mod
Mod(25, 35) // 12
should yield 5, because 5*12=60 which is 25 more the 35. 
The current implementation however leads to en error:
>> Mod(25, 35) // 12
ValueError: the value (25 % 35) cannot be inverted

Therefore I propose the change.